# 服务器相关配置
server:
  servlet:
    context-path: / # 为了便于开发此处省略应用程序上下文
  port: 8301 # 为了便于开发此处使用 http 默认端口

# spring 相关配置
spring:
  application:
    name: borrow-service
  config:
    import:
      - optional:nacos:mybatis-plus-dev.yml?refreshEnabled=true
      - optional:nacos:datasource-dev.yml?refreshEnabled=true
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 01224154-d186-4837-85a0-7a3de9602b82
      config:
        namespace: 01224154-d186-4837-85a0-7a3de9602b82

seata:
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: localhost:8868