# 服务器相关配置
server:
  servlet:
    context-path: / # 为了便于开发此处省略应用程序上下文
  port: 8301 # 为了便于开发此处使用 http 默认端口

# spring 相关配置
spring:
  application:
    name: borrow-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 01224154-d186-4837-85a0-7a3de9602b82
  datasource: # 数据库链接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.130.188:3306/cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 040905
    type: com.zaxxer.hikari.HikariDataSource

# mybatis-plus 相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将 mybatis 日志输出到控制台
    map-underscore-to-camel-case: true # 开启驼峰命名转换，需要类中字段名和表中列名相对应    cId => c_id
    cache-enabled: false # 是否开启二级缓存
    # 使用 mybatis-plus 的枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-aliases-package: org.qiaice.entity # 扫描指定包中的类，以避免写全类名
  mapper-locations: classpath:/mapper/**/*.xml # 扫描 mapper 文件
  global-config:
    db-config:
      id-type: auto # 设置主键增长策列
      update-strategy: not_null # 仅更新非空字段
      # 逻辑删除，对 sql 效率有影响，请斟酌使用
      # logic-delete-field: deleted # 逻辑删除字段名(实体类字段名)
      # logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      # logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)